### PR TITLE
Remove Blocklisten/malware false positive dns.digitale-gesellschaft.ch

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Doesn't look like a compromised domain but a false positive.

Reference:

- https://www.urlvoid.com/scan/dns.digitale-gesellschaft.ch/
- https://www.virustotal.com/gui/domain/dns.digitale-gesellschaft.ch/details

Also not blocked by the protective DNS below(tested via https://github.com/PeterDaveHello/chkdomain)
 - Comodo
 - UltraDNS
 - SafeDNS
 - OpenDNS
 - Cloudflare
 - Yandex
 - CONTROL D
 - Quad9
 - CleanBrowsing

### CODE REVIEW

**Comment by RPiList** [comment]
Pull requests for the malware list will not be merged. If it's a false positive, it will be removed automatically. Greetings

**Comment by PeterDaveHello** [comment]
Hi @RPiList, I saw that there were some PRs for FP removal, like #787 and #786, and they're merged, may I confirm the process of automatic removal? What's the best way to make sure false positives can be removed in time? Thanks!

**Comment by RPiList** [comment]
I investigated the source of blocking and it seems that our list-source 
 
https://github.com/notracking/hosts-blocklists is blocking the domain.

**Comment by RPiList** [comment]
Since dns.digitale-gesellschaft.ch is not even a webpage it is quite hard to understand how they should have put malware on the site. Looks like this is just their DNS-Resolver.

So I will whitelist the domain on our malware-list. Greetings.

**Comment by hagezi** [comment]
> I investigated the source of blocking and it seems that our list-source
> 
> https://github.com/notracking/hosts-blocklists is blocking the domain.

ping @notracking

**Pull request closed without merging**
