### PR TITLE
Delete .github directory

### PR DESCRIPTION
**Pull request by LizenzFass78851**
If you are concerned that the github directory is not useful or even dangerous because you can do damage with workflows, then you are welcome to delete it.

### CODE REVIEW

**Comment by RPiList** [comment]
> If you are concerned that the github directory is not useful or even dangerous 

Is there a reason to be concerned? I am not concerned but I may be not getting the complete picture.

**Comment by LizenzFass78851** [comment]
> Is there a reason to be concerned? I am not concerned but I may be not getting the complete picture.

In principle there is no reason to worry, but assuming that something changes in the directory, the workflows may encounter errors. In other words, manual adjustments are necessary anyway if something new is to be processed by the workflows. That is why I am of the opinion that the .github directory in question should be deleted. The Readme's would have to be manually adjusted anyway if the names of the lists are changed, so it can be ensured that the commit is not broken.

**Comment by thomasmerz** [comment]
I think this broke [GitHub Actions](https://github.com/RPiList/specials/actions) for "generate selected *.md files"?! Last Run 3 Months ago… 🤔 @RPiList and @LizenzFass78851

**Comment by LizenzFass78851** [comment]
I wanted to remove it because I'm not sure whether the workflows run maintenance-free.
Because the github action works reliably, but at one point it wouldn't work so well, assuming something changes in the directory structure of the repo and that is where the functionality of the github action depends.
If the directory structure changes, e.g. if the "Blocklisten" folder is renamed or if other directory names that are hard-coded into the script change, then there are errors and it would be possible to fix that, but it would fill up @RPiList's inbox because github sends him an email when an from the github action reported error.
In addition, when the developers of pihole release v6, the repo will definitely change directories due to the possible introduction of their own whitelists, assuming that a real restructuring of the directories is planned. (which I can't prove in any case).

@RPiList is welcome to undo the merge of this pull request and thus reactivate the workflows, but as I said, it is unfortunately not completely maintenance-free.

**Pull request merged**
