### PR TITLE
Remove filehosts from blocklist

### PR DESCRIPTION
**Pull request by JulianGro**
These are perfectly normal filehosts.
The only thing special about them is that you get direct download links from them.

### CODE REVIEW

**Comment by RPiList** [comment]
I am afraid, a.pomf.cat has to stay in the list because its a tracking domain which is regarded as malware by some maintainers.

files.catbox.moe will be removed in future updates.

Thanks for letting us know. Greetings.

**Comment by JulianGro** [comment]
What do you mean with "a tracking domain"?
It is where files uploaded to pomf.cat are hosted.

**Comment by RPiList** [comment]
Tracking is usually considered as a form of malware. Thats why it has been listed in the malware list.

It's quite common to use a subdomain for tracking. So pomf.cat is working perfectly. Just a.pomf.cat is blocked. Because of tracking.

**Comment by JulianGro** [comment]
Yeah but what sort of tracking is it supposed to be doing?
I mean everything you do on youtube is tracked and Youtube isn't blocked.
`a.pomf.cat` is just a download server. Like if I download a picture, what does it track? Surely it can only check my user agent and IP?

**Pull request closed without merging**
